Declare @condition_id int
EXEC msdb.dbo.sp_syspolicy_add_condition @name=N'SqlDeep_CheckTraceFlagsCondition', @description=N'Standard Trace Flags does not set correctly', @facet=N'Server', @expression=N'<Operator>
  <TypeClass>Bool</TypeClass>
  <OpType>AND</OpType>
  <Count>2</Count>
  <Operator>
    <TypeClass>Bool</TypeClass>
    <OpType>AND</OpType>
    <Count>2</Count>
    <Operator>
      <TypeClass>Bool</TypeClass>
      <OpType>AND</OpType>
      <Count>2</Count>
      <Operator>
        <TypeClass>Bool</TypeClass>
        <OpType>AND</OpType>
        <Count>2</Count>
        <Operator>
          <TypeClass>Bool</TypeClass>
          <OpType>AND</OpType>
          <Count>2</Count>
          <Operator>
            <TypeClass>Bool</TypeClass>
            <OpType>EQ</OpType>
            <Count>2</Count>
            <Function>
              <TypeClass>Numeric</TypeClass>
              <FunctionType>ExecuteSql</FunctionType>
              <ReturnType>Numeric</ReturnType>
              <Count>2</Count>
              <Constant>
                <TypeClass>String</TypeClass>
                <ObjType>System.String</ObjType>
                <Value>Numeric</Value>
              </Constant>
              <Constant>
                <TypeClass>String</TypeClass>
                <ObjType>System.String</ObjType>
                <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 1117</Value>
              </Constant>
            </Function>
            <Constant>
              <TypeClass>Numeric</TypeClass>
              <ObjType>System.Double</ObjType>
              <Value>1</Value>
            </Constant>
          </Operator>
          <Operator>
            <TypeClass>Bool</TypeClass>
            <OpType>EQ</OpType>
            <Count>2</Count>
            <Function>
              <TypeClass>Numeric</TypeClass>
              <FunctionType>ExecuteSql</FunctionType>
              <ReturnType>Numeric</ReturnType>
              <Count>2</Count>
              <Constant>
                <TypeClass>String</TypeClass>
                <ObjType>System.String</ObjType>
                <Value>Numeric</Value>
              </Constant>
              <Constant>
                <TypeClass>String</TypeClass>
                <ObjType>System.String</ObjType>
                <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 1118</Value>
              </Constant>
            </Function>
            <Constant>
              <TypeClass>Numeric</TypeClass>
              <ObjType>System.Double</ObjType>
              <Value>1</Value>
            </Constant>
          </Operator>
        </Operator>
        <Operator>
          <TypeClass>Bool</TypeClass>
          <OpType>EQ</OpType>
          <Count>2</Count>
          <Function>
            <TypeClass>Numeric</TypeClass>
            <FunctionType>ExecuteSql</FunctionType>
            <ReturnType>Numeric</ReturnType>
            <Count>2</Count>
            <Constant>
              <TypeClass>String</TypeClass>
              <ObjType>System.String</ObjType>
              <Value>Numeric</Value>
            </Constant>
            <Constant>
              <TypeClass>String</TypeClass>
              <ObjType>System.String</ObjType>
              <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 2371</Value>
            </Constant>
          </Function>
          <Constant>
            <TypeClass>Numeric</TypeClass>
            <ObjType>System.Double</ObjType>
            <Value>1</Value>
          </Constant>
        </Operator>
      </Operator>
      <Operator>
        <TypeClass>Bool</TypeClass>
        <OpType>EQ</OpType>
        <Count>2</Count>
        <Function>
          <TypeClass>Numeric</TypeClass>
          <FunctionType>ExecuteSql</FunctionType>
          <ReturnType>Numeric</ReturnType>
          <Count>2</Count>
          <Constant>
            <TypeClass>String</TypeClass>
            <ObjType>System.String</ObjType>
            <Value>Numeric</Value>
          </Constant>
          <Constant>
            <TypeClass>String</TypeClass>
            <ObjType>System.String</ObjType>
            <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 2549</Value>
          </Constant>
        </Function>
        <Constant>
          <TypeClass>Numeric</TypeClass>
          <ObjType>System.Double</ObjType>
          <Value>1</Value>
        </Constant>
      </Operator>
    </Operator>
    <Operator>
      <TypeClass>Bool</TypeClass>
      <OpType>EQ</OpType>
      <Count>2</Count>
      <Function>
        <TypeClass>Numeric</TypeClass>
        <FunctionType>ExecuteSql</FunctionType>
        <ReturnType>Numeric</ReturnType>
        <Count>2</Count>
        <Constant>
          <TypeClass>String</TypeClass>
          <ObjType>System.String</ObjType>
          <Value>Numeric</Value>
        </Constant>
        <Constant>
          <TypeClass>String</TypeClass>
          <ObjType>System.String</ObjType>
          <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 2562</Value>
        </Constant>
      </Function>
      <Constant>
        <TypeClass>Numeric</TypeClass>
        <ObjType>System.Double</ObjType>
        <Value>1</Value>
      </Constant>
    </Operator>
  </Operator>
  <Operator>
    <TypeClass>Bool</TypeClass>
    <OpType>EQ</OpType>
    <Count>2</Count>
    <Function>
      <TypeClass>Numeric</TypeClass>
      <FunctionType>ExecuteSql</FunctionType>
      <ReturnType>Numeric</ReturnType>
      <Count>2</Count>
      <Constant>
        <TypeClass>String</TypeClass>
        <ObjType>System.String</ObjType>
        <Value>Numeric</Value>
      </Constant>
      <Constant>
        <TypeClass>String</TypeClass>
        <ObjType>System.String</ObjType>
        <Value>EXECUTE [SqlDeep].[dbo].[dbasp_policycheck_traceflag] 4199</Value>
      </Constant>
    </Function>
    <Constant>
      <TypeClass>Numeric</TypeClass>
      <ObjType>System.Double</ObjType>
      <Value>1</Value>
    </Constant>
  </Operator>
</Operator>', @is_name_condition=0, @obj_name=N'', @condition_id=@condition_id OUTPUT
Select @condition_id

GO

