USE [master]
GO
DENY CONNECT SQL TO [NT SERVICE\SQLTELEMETRY$NODE]
GO
ALTER LOGIN [NT SERVICE\SQLTELEMETRY$NODE] DISABLE
GO
DENY CONNECT SQL TO [NT SERVICE\SQLTELEMETRY]
GO
ALTER LOGIN [NT SERVICE\SQLTELEMETRY] DISABLE
GO
